### ISSUE TITLE
Unix composability

### ISSUE THREAD

**Issue by dcousens** [auditdrivencrypto/secure-channel#12]
This is still a long ways off, however:

Server (`10.0.0.2`)
`ncat -l 5000 | secure-channel --authorized=~/.sckeys`

Client
`echo "hello world" | secure-channel --key~/.mysckey | ncat 10.0.0.2 5000`

Would be an awesome way to compose this.
Obviously a handshake would occur, and the eventual result is the server prints the text `"hello world"` to the console.

KISS secure channels.

**Comment by dcousens** [comment]
The main point is extracting the encryption/decryption to a different layer.
You'll probably still want to include authorization verification in the underlying applications, whatever they are.

**Comment by dominictarr** [comment]
Yeah this would be neat, but unfortunately there isn't a really nice way to create servers in bash.
I guess that it was originally designed to be a work processor (hence all the programs that work with streams of text)

Actually piping this to netcat wouldn't work, because this needs to send data both ways.
The best thing you could do would be to pass in a command that secure-channel would call to create a connection, and it would then hold both the `stdin` and `stdout`.

**Comment by dominictarr** [comment]
more like:

`echo 'hello world' | secure-channel --keys ... --connect 'netcat ...'`

**Comment by dcousens** [comment]
You could use a [single named pipe](https://unix.stackexchange.com/questions/53641/how-to-make-bidirectional-pipe-between-two-programs#comment75046_53646), among many other ways mentioned there.

**Comment by dominictarr** [comment]
true. what about if you passed the named pipe to the command and it could detect that it's a fifo and not a command?

that named pipe thing is good, but you'd also need a way to get the plaintext in and out - that is also duplex.
So actually you have 4 stdio streams. plainin, plainout, cipherin, cipherout. I think passing in the fifo/cmd would be the easiest way to do that.

**Comment by dcousens** [comment]
True.  I'll get back to you.  Haha.

**Comment by dcousens** [comment]
I can't see this being very simple if you need to negotiate keys.
For an a symmetric cipher... definitely,  but there already tools for that. 

The asymmetry is what makes this non simple.
